# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 3.15)
   message(FATAL_ERROR "CMake >= 3.15.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget hip::galaxyhip hip::host hip::device)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)

# The installation prefix configured by this project.
set(_IMPORT_PREFIX "${ROCM_PATH}/hip")

# Create imported target hip::galaxyhip
add_library(hip::galaxyhip SHARED IMPORTED)

set_property(TARGET hip::galaxyhip APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)

# Import target "hip::galaxyhip" for configuration "Release"
find_library( _GALAXYHIP_SO NAMES galaxyhip libgalaxyhip
              PATHS ${_IMPORT_PREFIX}/lib
              REQUIRED
              NO_DEFAULT_PATH
              NO_CMAKE_ENVIRONMENT_PATH
              NO_CMAKE_PATH
              NO_SYSTEM_ENVIRONMENT_PATH
              NO_CMAKE_SYSTEM_PATH)
set_target_properties(hip::galaxyhip PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_GALAXYHIP_SO}"
  IMPORTED_SONAME_RELEASE "${_GALAXYHIP_SO}"
  )
list(APPEND _IMPORT_CHECK_TARGETS hip::galaxyhip)
list(APPEND _IMPORT_CHECK_FILES_FOR_hip::galaxyhip "${_GALAXYHIP_SO}")

# Create imported target hip::host
add_library(hip::host INTERFACE IMPORTED)

set_target_properties(hip::host PROPERTIES
  INTERFACE_LINK_LIBRARIES "hip::galaxyhip"
)

# Create imported target hip::device
add_library(hip::device INTERFACE IMPORTED)

set_target_properties(hip::device PROPERTIES
  INTERFACE_LINK_LIBRARIES "hip::host"
)

set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
